# -*- coding: utf-8 -*-
"""task_reminder

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/124xV9NLxe7j-Fk2YbaKegzpXhFQ_UcO9
"""

import time
from datetime import datetime

def task_reminder():
    task = input("Enter task name: ")
    seconds = int(input("Reminder after how many seconds? "))

    current_time = datetime.now().strftime("%H:%M:%S")
    print(f"\nCurrent Time: {current_time}")
    print(f"Reminder set for '{task}' in {seconds} seconds...")

    time.sleep(seconds)

    alert_time = datetime.now().strftime("%H:%M:%S")
    print(f"\n🔔 [{alert_time}] Reminder: Time to {task}!")

task_reminder()

